-- MySQL Script generated by MySQL Workbench
-- Sun Dec  8 16:22:59 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vlados
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vlados
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vlados` DEFAULT CHARACTER SET utf8 ;
USE `vlados` ;

-- -----------------------------------------------------
-- Table `vlados`.`film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vlados`.`film` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `genre` VARCHAR(45) NOT NULL,
  `producers` VARCHAR(255) NOT NULL,
  `main_roles` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vlados`.`session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vlados`.`session` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `date_time` DATETIME NOT NULL,
  `price` DECIMAL(10,0) NOT NULL,
  `film_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`, `film_id`),
  INDEX `fk_session_film_idx` (`film_id` ASC) VISIBLE,
  CONSTRAINT `fk_session_film`
    FOREIGN KEY (`film_id`)
    REFERENCES `vlados`.`film` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vlados`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vlados`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vlados`.`basket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vlados`.`basket` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `session_id` BIGINT NOT NULL,
  PRIMARY KEY (`user_id`, `session_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vlados`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vlados`.`client` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `cash` DECIMAL(10,0) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vlados`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vlados`.`ticket` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `session_id` BIGINT NOT NULL,
  PRIMARY KEY (`user_id`, `session_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
